[package]
name = "client"
version = "0.1.0"
authors = ["Patrik Sjöberg <voxar@dyna.mo>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enet = "0.2.2"